---
apiVersion: v1
kind: Namespace
metadata:
  name: kuma-example
  labels:
    kuma.io/sidecar-injection: enabled

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-config
  namespace: kuma-example
data:
  kong.yml: |
    _format_version: "1.1"

    services:
    - name: mockbin.org
      url: http://mockbin.org
      routes:
      - name: default
        paths:
        - /
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: kuma-example
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: example-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app-service-account
  namespace: kuma-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kuma-example
  labels:
    app: example-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      serviceAccountName: example-app-service-account
      containers:
      - name: example-app
        image: "kong:1.1.2-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: KONG_ADMIN_LISTEN
          value: "off"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/etc/kong/kong.yml"
        volumeMounts:
        - name: example-app-config
          mountPath: /etc/kong
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        readinessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: example-app-config
        configMap:
          name: example-app-config

---
apiVersion: v1
kind: Service
metadata:
  name: example-client
  namespace: kuma-example
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: example-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-client-service-account
  namespace: kuma-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-client
  namespace: kuma-example
  labels:
    app: example-client
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: example-client
  template:
    metadata:
      labels:
        app: example-client
    spec:
      serviceAccountName: example-client-service-account
      containers:
      - name: example-client
        image: kong-docker-kuma-ci-docker.bintray.io/curl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        command:
        - nc
        - -lk
        - -p
        - "3000"
        - -e
        - curl
        - --silent
        - --show-error
        - --include
        - --fail
        - http://example-app.kuma-example:8000/request
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
